Removed cvxcanon... conda barfed...
UnsatisfiableError: The following specifications were found to be in conflict:
  - cvxcanon -> python 2.7*
  - python 3.6*